
spring:
  application:
    name: getionProfile
  datasource:
    url: jdbc:mysql://localhost:3306/etudiant
    username: root
    password: thisislife1721_
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: comment-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
    properties:
      spring.json.type.mapping: comment:hazy.gestionProfile.Comments.Comment.Comment
      spring.json.trusted.packages: hazy.gestionProfile.Comments.Comment

server:
  port: 1016